[env]
CUDA_PATH = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2"
CUDACXX = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\bin\\nvcc.exe"
CMAKE_GENERATOR = "Ninja"
CMAKE_MAKE_PROGRAM = "C:\\Users\\silve\\ninja\\ninja.exe"
CMAKE_CUDA_FLAGS = "--allow-unsupported-compiler"
CMAKE_CUDA_COMPILER = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2\\bin\\nvcc.exe"